### ISSUE TITLE
docs: `Default` is not implemented for EmitterShape

### ISSUE THREAD

**Issue by johanhelsing** [abnormalbrain/bevy_particle_systems#36]
The docs say that `CircleSegment::opening_angle` will default to tau, but `EmitterShape` doesn't implement `Default`. That is, the following doesn't compile:

```rust
emitter_shape: EmitterShape::CircleSegment {
    radius: 0.0.,
    direction_angle: PI * 3. / 2.,
    ..default()
},
```

**Comment by abnormalbrain** [comment]
Ah, looks like an oversight in the transition of the previous emitter angle to `EmitterShape`.

**Comment by abnormalbrain** [comment]
So unfortunately, I don't think it's possible to define defaults for enum variants specifically, such that the code block here would work. So in order to achieve this we'll have to introduce inner structs that have a default. e.x.

```
emitter_shape: EmitterShape::CircleSegment(CircleSegment {
    radius: 0.0,
    direction_angle: PI * 3.0 / 2.0,
    ..default()
}),
```

Which maybe we can shorten to 

```
emitter_angle: CircleSegment {
    // ...
    ..default()
}.into()
```

**Comment by johanhelsing** [comment]
Yes, I think I've seen this pattern in quite a few places actually. I guess an alternative would be to make a few helper constructor methods on `EmitterShape`. i.e

```rust
emitter_shape: EmitterShape::circle(0.0..0.50.into())
```

```rust
emitter_shape: EmitterShape::circle_edge(0.5)
```

**Comment by abnormalbrain** [comment]
@johanhelsing Check out #38 and see what you think.
