### ISSUE TITLE
Add Gradient-like value for ValueOverTime ?

### ISSUE THREAD

**Issue by Rayoule** [abnormalbrain/bevy_particle_systems#39]

**Comment by Rayoule** [comment]
Sorry I don't know how to cancel an issue. I don't think it is that interesting to have this ValueOverTime

**Comment by abnormalbrain** [comment]
@Rayoule I can close this issue, but if you're looking to achieve something specific and need help on how to do it, feel free to open an issue and label it with the "question" label, and I can help out or add missing capabilities if they make sense :)

**Comment by Rayoule** [comment]
Thanks, I will !
